dependencies:
  - name: git-chglog
    version: 0.15.4
    force-replace: true
    archive_url_template: https://github.com/git-chglog/git-chglog/releases/download/v{{.Version}}/git-chglog_{{.Version}}_{{.Os}}_{{.Arch}}.{{.Ext}}

commit:
  defaut_type: feat
  
  types:
    - type: feat
      description: a new feature is introduced with the changes
    - type: fix
      description: a bug fix has occurred
    - type: docs
      description: updates to documentation such as a the README or other markdown files
    - type: test
      description: including new or correcting previous tests
    - type: refactor
      description: refactored code that neither fixes a bug nor adds a feature
  
  dictionaries:
    - name: add
      value: add
      type: feat
      synonyms:
        - adds
        - added
        - adding
        - new
    - name: use
      value: use
      type: feat
      synonyms:
        - used
        - uses
    - name: update
      value: update
      type: refactor
      synonyms:
        - updated
        - updates
    - name: refactor
      value: refactor
      type: refactor
      synonyms:
        - change
        - changes
        - changed
        - restructure
        - restructured
        - restructures
    - name: remove
      value: remove
      type: refactor
      synonyms:
        - removed
        - removes
    - name: fix
      value: fix
      type: fix
      synonyms:
        - fixes
        - fixed
        - fixing
        - correct
